### PR TITLE
a somewhat WIP build for node

### PR DESCRIPTION
**Pull request by jamesadevine**

### CODE REVIEW

**Comment by jamesadevine** [comment]
@pelikhan there is a vm mode for node, so I'm just running jacdac in there. This is super cool because it means N jacdac devices can be created programmatically.

**Comment by pelikhan** [comment]
Yes!

**Comment by jamesadevine** [comment]
@pelikhan do you have a preference for faye? socket.io runs in the web browser too -- it's widely used IIRC

**Comment by pelikhan** [comment]
https://github.com/faye/faye-websocket-node It is just client though...

**Comment by jamesadevine** [comment]
@pelikhan This is overall pretty ugly, and hacky, but with some abstraction it is hidden quite well

https://github.com/jacdac/jacdac-ts/blob/f6ea5ec36d08ce9ad67f2b49b43dfb63e3720978/node/tests/send-rec-test.ts

For native node use, I think jacdac-ts would need to be rewritten

**Pull request merged**
